[package]
name = "mail_sender"
description = "The mail service is a simple wrapper around the `lettre` crate."
version = "1.0.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
tera = { workspace = true }
lettre = { workspace = true, default-features = false, features = [
  "smtp-transport",
  "tokio1-rustls-tls",
  "hostname",
  "builder",
] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
serde_json = "1.0.140"

[dev-dependencies]
tempfile = "3.19.0"
