[package]
name = "mail_sender"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "mail_sender"

[dependencies]
tera = "1.20.0"
thiserror = "2.0.12"
lettre = { version = "0.11.13", default-features = false, features = [
  "smtp-transport",
  "tokio1-rustls-tls",
  "hostname",
  "builder",
] }
tokio = { version = "1.43.0", features = ["full"] }
chrono = "0.4.40"

[dev-dependencies]
tempfile = "3.19.0"
