[package]
name = "mail_sender"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "mail_sender"

[dependencies]
tera = { workspace = true }
lettre = { workspace = true, default-features = false, features = [
  "smtp-transport",
  "tokio1-rustls-tls",
  "hostname",
  "builder",
] }
tokio = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = "3.19.0"
