CREATE TABLE IF NOT EXISTS email_logs (
  id SERIAL PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  to TEXT NOT NULL,
  cc TEXT,
  bcc TEXT,
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);